"""Initial migration with url_match_type and wait_seconds

Revision ID: fd6be61e2ca7
Revises: 
Create Date: 2025-07-08 23:14:15.918504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd6be61e2ca7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_match_type', sa.Enum('exact', 'regex', 'glob'), nullable=True))
        batch_op.alter_column('request_url_filter',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('request_url_filter',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('url_match_type')

    # ### end Alembic commands ###
